ifndef::imagesdir[:imagesdir: ../images]

[[section-solution-strategy]]
== Solution Strategy


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape system architecture. It includes

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the foundation for many other detailed decisions or implementation rules.

.Form
Keep the explanations of such key decisions short.

Motivate what was decided and why it was decided that way,
based upon problem statement, quality goals and key constraints.
Refer to details in the following sections.


.Further Information

See https://docs.arc42.org/section-4/[Solution Strategy] in the arc42 documentation.

****
endif::arc42help[]

=== Technology decisions
- **JavaScript:** It is the chosen programming language for this application. After comparing it with TypeScript, we concluded it is the best choice taking into account easiness in the use and team experience.
- **React:** We have chosen this JavaScript library for the UI because it is the industry standard and other alternatives don't provide any benefits compared to it and it's easy use.
- **Node.js:** We decided to use it so we use JavaScript both in the frontend and backend. Also, since Mongoose, which will be used to comunicate with the database, is a Node.js library, Node.js is a good option for this application.
- **Docker:** We chose it since several members of the team have experience with it and it's easy to learn for new users compared to other alternatives. Also, it's open-source and user friendly.
- **MongoDB:** We decided to use this document database due to its flexibility and simple query language.
- **Microsoft Azure:** We chose this platform since it provides the needed infrastructure and the team members have experience with it.
- **Express.js:** We have chosen this web application framework for Node.js due to its high flexibility, its easy use and learning and its powerful middleware.

=== Top-level decomposition decisions
- **Microservices pattern:** The Microservices architectural pattern is used, so the application is divided into different components with a responsibility each one. This makes the different components independent and low coupled, allowing mantainability.
Also, it reduces possible conflicts between the development carried out by the team members and the code dependencies.  
- **Gateway pattern:** This pattern is chosen because it allows to give the application a single request interface that redirects requests by the 
user to the appropiate application component. It is the appropiate pattern to complement the Microservices pattern due to these reasons.

=== Decisions to achieve key quality goals
- **Mantainability:** The application will be well structured and documented to allow a proper mantainability.
- **Usability:** A user-friendly application will be developed, as well as intuitive.
- **Testability:** Multiple tests will be performed on the application to ensure the proper functioning of the application and to ensure there are no errors.

=== Organizational decisions
- Use of a Github repository for the project.
- Weekly meeting of the team to review and discuss work done during the week, to take decisions for the project and assigning tasks that must be made.
- Communication between members and task assigning using Github Issues.
- For a quick and agile communication, use of a WhatsApp group of the team.
- Keep track of all the work done by the team using Github Projects, linking on it the different Issues. 
- Record the weekly meeting minutes and details and project decisions by means of Github Wiki.